### PR TITLE
Rename env vars TEMPORAL_CLI.. to TEMPORAL..

### PR DESCRIPTION
**Pull request by feedmeapples**
## What was changed

renamed env variables

## Why?

Consistency of env names. Shorter in --help output

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Review by samanbarghi — APPROVED** [review]

**Comment by taonic** [comment]
@feedmeapples Are you aware of any follow up action to update the doc too?

https://docs.temporal.io/cli#environmental-variables

**Comment by bergundy** [comment]
@feedmeapples we need to revert this change, it broke the usage in admintools. We rely on these env vars in too many samples.

**Comment by sahilvv** [comment]
This has broken the CLI in admin-tools/1.21.1. Need to export variables without CLI in VarName as a workaround.

**Comment by bergundy** [comment]
No, we’re staying with this new convention.
Why?

**Pull request merged**
